"""AlienCode v2 protocol: fixed calibration demos.

Exploration itself stays natural: the model writes AlienCode and the harness
executes exactly what it submitted, charged by observed values (see
``_count_show_weighted`` in ``run_eval``). What this module fixes is the
evidence every system carries into M0, so a run no longer starts from whatever
the model happened to probe during a free seed phase.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from typing import Any, Callable

from sandboxes.code import world_data

PROTOCOL_VERSION = "aliencode-v2-fixed-demos-2026-09-19"
DEFAULT_PROBES_PER_BLOCK = 12
DEFAULT_EXPLORE_BLOCKS = 4

# The rules the fixed worked examples expose. Recorded for the leakage audit,
# never shown to the model.
PUBLIC_DEMO_RULES = world_data.PUBLIC_DEMO_RULES


@dataclass(frozen=True)
class Demo:
    id: str
    band: str
    prompt: str
    code: str
    rules: tuple[str, ...]


DEMOS = tuple(Demo(**row) for row in world_data.DEMOS)


def demo_rows(executor: Callable[[str], str]) -> list[dict[str, Any]]:
    """Each demo with the output the real interpreter produces for it."""
    return [
        {
            "id": demo.id,
            "band": demo.band,
            "prompt": demo.prompt,
            "code": demo.code,
            "output": executor(demo.code),
            "rules": list(demo.rules),
        }
        for demo in DEMOS
    ]


def demo_block(executor: Callable[[str], str]) -> str:
    parts = [
        "AlienCode v2 fixed calibration demos.",
        f"These {len(DEMOS)} worked examples are the only evidence shown before M0. "
        "They are fixed across systems and are not generated by the model.",
    ]
    for row in demo_rows(executor):
        parts.append(
            f"\n[{row['id']} | {row['band']}]\n"
            f"Task: {row['prompt']}\n"
            "Canonical program:\n"
            f"```aliencode\n{row['code']}\n```\n"
            "Observed output:\n"
            f"```text\n{row['output']}\n```"
        )
    parts.append(
        "\nAfter these demos you get four exploration blocks. In each block you "
        "write your own AlienCode and run it with the tool; the environment "
        "returns the real output of exactly the code you submitted."
    )
    return "\n".join(parts)


def manifest(executor: Callable[[str], str]) -> dict[str, Any]:
    data = {
        "protocol_version": PROTOCOL_VERSION,
        "public_demo_rules": list(PUBLIC_DEMO_RULES),
        "default_explore_blocks": DEFAULT_EXPLORE_BLOCKS,
        "default_probes_per_block": DEFAULT_PROBES_PER_BLOCK,
        "demos": demo_rows(executor),
    }
    blob = json.dumps(data, ensure_ascii=False, sort_keys=True).encode()
    data["sha256"] = hashlib.sha256(blob).hexdigest()
    return data
